import { hostname as osHostname, userInfo } from 'node:os';
import { ConcurrentUpdateError } from '@pulumi/pulumi/automation/index.js';
import type { ElectronStoreService } from './ElectronStoreService.js';

/**
 * Task 4.8's stale-backend-lock-recovery primitives, satisfying the
 * `pulumi-engine-runtime` delta spec's "Stale backend lock recovery"
 * requirement.
 *
 * ## Verified: the exact message shape a DIY-backend lock conflict produces
 *
 * The self-managed (DIY/`file://`/`s3://`) backend's lock-conflict message is
 * generated by `checkForLock` in the Pulumi CLI's Go source
 * (`pkg/backend/diy/lock.go`, fetched from the `pulumi/pulumi` GitHub repo's
 * `master` branch during this task's investigation — the Go source is not vendored into this repo's
 * `node_modules`, since only the compiled CLI binary and the Node Automation
 * API SDK are):
 *
 * ```go
 * type lockContent struct {
 *     Pid       int       `json:"pid"`
 *     Username  string    `json:"username"`
 *     Hostname  string    `json:"hostname"`
 *     Timestamp time.Time `json:"timestamp"`
 * }
 *
 * fmt.Fprintf(&errorString, "the stack is currently locked by %v lock(s). Either wait for the other "+
 *     "process(es) to end or delete the lock file with `pulumi cancel`.", len(lockKeys))
 * for _, lock := range lockKeys {
 *     // ...
 *     fmt.Fprintf(&errorString, "\n  %v: created by %v@%v (pid %v) at %v",
 *         b.lockURLForError(lock), l.Username, l.Hostname, l.Pid, l.Timestamp.Format(time.RFC3339))
 * }
 * ```
 *
 * This confirms design.md's `"the stack is currently locked by"` match
 * string exactly, and — going further than design.md states — shows the
 * message is **structured and parseable**: each lock file still present gets
 * its own line naming the lock's URL, the OS username and hostname of the
 * process that created it, that process's PID, and an RFC3339 creation
 * timestamp. {@link parseStackLocks} below parses exactly this shape. The
 * Node SDK's own `errors.js` (`node_modules/@pulumi/pulumi/automation/errors.js`)
 * wraps any CLI failure whose stderr contains this text (or the Pulumi
 * Cloud-only `"[409] Conflict: ..."` text) in a `ConcurrentUpdateError` —
 * checked first below via `instanceof`, with the message-pattern match kept
 * only as the same best-effort backstop `PulumiWorkspaceService`'s
 * `looksLikeMissingBucket` already uses for a different failure shape.
 *
 * ## Why "provable ownership" is the CLI's PID, not ours
 *
 * `lockContent.Pid`/`.Username`/`.Hostname` are properties of the **`pulumi`
 * CLI child process itself** (`os.Getpid()`/`user.Current()`/`os.Hostname()`
 * in Go), not of this Electron app. As established in `PulumiCancellation.ts`'s
 * TSDoc, the Automation API never exposes that child process's PID to this
 * app — so this app can never record, in advance, the exact PID a future lock
 * file will carry, and cannot match on it. `Username`/`Hostname`, however,
 * are inherited from the OS session the CLI child is spawned under — the
 * *same* OS user and machine this Electron process itself is running as
 * (`os.userInfo().username`/`os.hostname()`). Every lock this installation
 * ever causes to be taken will carry exactly this app's own
 * username/hostname pair, which is therefore the finest-grained proof
 * available through documented means. This is an honest limitation, not a
 * gap in this task: it cannot distinguish two *separate* installations of
 * this app running under the same OS user on the same machine (an
 * unsupported, unlikely configuration) from one installation's own orphaned
 * run — see this task's report for this noted as a residual concern.
 *
 * {@link classifyStackLockConflict} combines this identity match with
 * {@link ElectronStoreService.listPulumiLockAttempts} — this installation's
 * own record of runs it caused to reach the SDK — so a lock is only ever
 * classified as a provable own orphan when **both** (a) every parsed lock
 * entry's username/hostname matches this machine's own, **and** (b) this
 * installation has an outstanding (never-cleared) record of having actually
 * started an attempt against the same stack. Absence of an in-flight
 * operation is deliberately *not* part of this test on its own — per the
 * spec's "Another machine's active lock is not presented as stale" and
 * "In-app concurrency is reported as busy" scenarios, that distinction is
 * made by a layer above this module (the workspace-in-flight/"busy" check
 * `TerraformService.getWorkspaceInFlight()` already establishes the
 * precedent for — see `terraform.controller.ts`), *before* an operation ever
 * reaches the SDK call this module's classifier reacts to. This module only
 * ever runs once a `ConcurrentUpdateError` has actually been thrown by the
 * backend, which cannot happen for an operation this same instance is
 * concurrently running against its own reused, single workspace.
 */

/**
 * One parsed lock entry from a DIY-backend "currently locked" conflict
 * message — see this file's top-level TSDoc for the verified Go source this
 * targets.
 */
export interface PulumiStackLockInfo {
  /** The lock object's URL, as rendered by the CLI's own `lockURLForError` (credentials already redacted by the CLI). */
  lockUrl: string;
  /** OS username of the process that created the lock (`user.Current().Username` in the Go CLI). */
  username: string;
  /** OS hostname of the machine that created the lock (`os.Hostname()` in the Go CLI). */
  hostname: string;
  /** PID of the `pulumi` CLI process that created the lock — a property of that (long-exited) process, not observable or controllable from this app. */
  pid: number;
  /** When the lock was created, parsed from the CLI's RFC3339 timestamp. */
  lockedAt: Date;
}

/** Matches each per-lock detail line the Go CLI appends — see this file's top-level TSDoc for the exact `fmt.Fprintf` format this mirrors. */
const LOCK_ENTRY_PATTERN = /^\s*(\S+):\s*created by (\S+)@(\S+) \(pid (\d+)\) at (.+)$/gm;

/** Matches the Pulumi Cloud (non-DIY) backend's conflict text — see design.md and `errors.js`'s `conflictText`. Carries no structured holder/age detail, unlike the DIY-backend shape {@link LOCK_ENTRY_PATTERN} parses. */
const SERVICE_BACKEND_CONFLICT_PATTERN = /\[409\] Conflict/;

/** Matches the DIY-backend conflict summary line — see `errors.js`'s `diyBackendConflictText` and this file's top-level TSDoc. */
const DIY_BACKEND_CONFLICT_PATTERN = /the stack is currently locked by/i;

/**
 * True when `err` represents the backend refusing an operation because the
 * stack is locked — matched primarily via `instanceof ConcurrentUpdateError`
 * (the SDK's own typed class for this, per `errors.js`'s `createCommandError`),
 * with a message-pattern match kept only as a best-effort backstop for an
 * error that reached this code some other way (e.g. re-thrown/re-wrapped
 * upstream). Distinguishing this from "in-app busy" is **not** this
 * function's job — see this file's top-level TSDoc's "Why provable ownership"
 * section for why an in-app conflict never reaches this function at all.
 */
export function isStackLockConflict(err: unknown): boolean {
  if (err instanceof ConcurrentUpdateError) return true;
  const message = err instanceof Error ? err.message : String(err);
  return DIY_BACKEND_CONFLICT_PATTERN.test(message) || SERVICE_BACKEND_CONFLICT_PATTERN.test(message);
}

/**
 * Best-effort parse of every structured lock entry out of `err`'s message —
 * see {@link LOCK_ENTRY_PATTERN} and this file's top-level TSDoc for the
 * exact shape this targets. Returns an empty array (never throws) when `err`
 * is a lock conflict but carries no parseable per-lock detail (e.g. the
 * Pulumi Cloud backend's `"[409] Conflict"` text, which this app never
 * actually produces since it always uses the DIY backend — see the
 * `pulumi-engine-runtime` delta spec's "Automation API workspace seam"
 * requirement — but is handled defensively rather than assumed away), or
 * when `err` is not a lock conflict at all.
 */
export function parseStackLocks(err: unknown): PulumiStackLockInfo[] {
  const message = err instanceof Error ? err.message : String(err);
  const locks: PulumiStackLockInfo[] = [];
  for (const match of message.matchAll(LOCK_ENTRY_PATTERN)) {
    const [, lockUrl, username, hostname, pid, timestamp] = match;
    const lockedAt = new Date(timestamp);
    // Defensive: skip a line whose timestamp doesn't parse rather than
    // propagate an `Invalid Date` into a classification/confirmation-error
    // downstream consumers would otherwise have to guard against themselves.
    if (Number.isNaN(lockedAt.getTime())) continue;
    locks.push({ lockUrl, username, hostname, pid: Number(pid), lockedAt });
  }
  return locks;
}

/**
 * The three outcomes {@link classifyStackLockConflict} can reach. Does not
 * include "in-app busy" — see this file's top-level TSDoc for why that
 * category is handled by a layer above this module and never reaches a
 * `ConcurrentUpdateError` in the first place.
 */
export type PulumiLockClassification =
  | { kind: 'not-a-lock-conflict' }
  | { kind: 'reclaimable-own-orphan'; locks: PulumiStackLockInfo[] }
  | { kind: 'requires-confirmation'; locks: PulumiStackLockInfo[] };

/**
 * Classifies a caught error against the `pulumi-engine-runtime` delta spec's
 * "Stale backend lock recovery" requirement's provable-ownership test — see
 * this file's top-level TSDoc for the full reasoning.
 *
 * A lock is `'reclaimable-own-orphan'` only when **every** parsed lock entry
 * matches `identity` (defaults to this machine's own `os.userInfo().username`/
 * `os.hostname()`) **and** `store` has at least one outstanding (never
 * cleared via `ElectronStoreService.clearPulumiLockAttempt`) record for
 * `stackName` — i.e. this installation both plausibly could have created
 * every lock present, and has direct evidence it started an attempt against
 * this stack that never reported completing normally. Requiring *every*
 * lock to match (not just one) matters because `stack.cancel()` — the
 * mechanism design.md reserves for actually clearing a stale lock — is not
 * scoped to a single lock file; reclaiming when even one present lock
 * belongs to someone else would improperly clear their lock too.
 *
 * Anything else — no parsed locks at all, a lock whose identity doesn't
 * match, or no outstanding local record — is `'requires-confirmation'`,
 * carrying whatever locks *were* parsed (possibly none) for the caller to
 * surface via {@link PulumiUnrecognizedLockError}.
 */
export function classifyStackLockConflict(
  err: unknown,
  store: ElectronStoreService,
  stackName: string,
  identity: { username: string; hostname: string } = { username: userInfo().username, hostname: osHostname() },
): PulumiLockClassification {
  if (!isStackLockConflict(err)) {
    return { kind: 'not-a-lock-conflict' };
  }

  const locks = parseStackLocks(err);
  const hasOutstandingRecord = store.listPulumiLockAttempts(stackName).length > 0;
  const everyLockIsOurs =
    locks.length > 0 && locks.every((lock) => lock.username === identity.username && lock.hostname === identity.hostname);

  if (hasOutstandingRecord && everyLockIsOurs) {
    return { kind: 'reclaimable-own-orphan', locks };
  }
  return { kind: 'requires-confirmation', locks };
}

/**
 * Formats how long ago `lockedAt` was, for the confirmation prompt's "age"
 * display (`pulumi-engine-runtime`'s "Unrecognised lock requires
 * confirmation with evidence" scenario: "...the recorded holder, and the
 * lock's age"). Deliberately coarse (minutes/hours/days) rather than exact —
 * a stale-lock confirmation dialog cares whether a lock is "5 minutes old"
 * (plausibly still in progress — pause and check) vs. "3 days old"
 * (plausibly abandoned), not second-level precision.
 *
 * @param lockedAt - When the lock was created (see {@link PulumiStackLockInfo.lockedAt}).
 * @param now - Injectable for tests; defaults to the real current time.
 */
export function formatLockAge(lockedAt: Date, now: Date = new Date()): string {
  const ms = Math.max(0, now.getTime() - lockedAt.getTime());
  const minutes = Math.floor(ms / 60_000);
  if (minutes < 1) return 'less than a minute ago';
  if (minutes < 60) return `${minutes} minute${minutes === 1 ? '' : 's'} ago`;
  const hours = Math.floor(minutes / 60);
  if (hours < 24) return `${hours} hour${hours === 1 ? '' : 's'} ago`;
  const days = Math.floor(hours / 24);
  return `${days} day${days === 1 ? '' : 's'} ago`;
}

/**
 * Thrown when a backend lock conflict cannot be proven to belong to this
 * installation — the `pulumi-engine-runtime` delta spec's "Unrecognised lock
 * requires confirmation with evidence" scenario. Carries `locks` (holder +
 * age, via {@link PulumiStackLockInfo.lockedAt}/{@link formatLockAge}) for
 * Phase 9's confirmation UI to render; nothing is cleared until the operator
 * explicitly confirms — this class only *reports* the condition, it never
 * calls `stack.cancel()` itself.
 *
 * There is deliberately no equivalent `PulumiReclaimableLockError` — the
 * `'reclaimable-own-orphan'` classification is not surfaced to the operator
 * at all (per spec: "The app MAY reclaim it without prompting"); Phase 7's
 * caller acts on that classification directly (calling `stack.cancel()` and
 * retrying) without ever constructing or throwing an error for it.
 */
export class PulumiUnrecognizedLockError extends Error {
  constructor(
    public readonly stackName: string,
    public readonly locks: PulumiStackLockInfo[],
  ) {
    super(describeUnrecognizedLock(stackName, locks));
    this.name = 'PulumiUnrecognizedLockError';
  }
}

function describeUnrecognizedLock(stackName: string, locks: PulumiStackLockInfo[]): string {
  if (locks.length === 0) {
    return (
      `Cannot run this Pulumi operation: the stack "${stackName}" is locked, but this installation cannot ` +
      'determine who holds the lock or how long ago it was taken. Confirm the lock is genuinely stale ' +
      '(e.g. a crashed run on another machine) before clearing it.'
    );
  }
  const holders = locks
    .map((lock) => `${lock.username}@${lock.hostname} (pid ${lock.pid}), ${formatLockAge(lock.lockedAt)}`)
    .join('; ');
  return (
    `Cannot run this Pulumi operation: the stack "${stackName}" is locked by ${holders}. This installation ` +
    'cannot prove it owns this lock — confirm it is genuinely stale before clearing it.'
  );
}
